import type { CctvCamera } from './types';

/**
 * TRINETRA — Comprehensive Live CCTV & Webcams Network Across India
 *
 * Covers all requested states & major hubs:
 * - Maharashtra (Mumbai, Pune, Shirdi, Nanded, Nagpur, Nashik)
 * - Delhi NCR (Connaught Place, India Gate, DND, Gurugram, Noida, Aerocity)
 * - Karnataka (Bengaluru, Mysuru, Mangaluru, Hubballi)
 * - Tamil Nadu (Chennai, Madurai, Coimbatore, Kanyakumari)
 * - Kerala (Kochi, Thiruvananthapuram, Kozhikode, Munnar, Alappuzha)
 * - Uttar Pradesh (Varanasi, Ayodhya, Agra, Lucknow, Mathura, Noida)
 * - West Bengal (Kolkata, Darjeeling, Siliguri, Digha)
 * - Odisha (Puri, Bhubaneswar, Cuttack, Paradip Port, Rourkela)
 * - Gujarat (Ahmedabad, Surat, Somnath, Dwarka, Vadodara)
 * - Goa (Calangute, Panaji Atal Setu, Baga, Mormugao)
 * - Telangana & Andhra Pradesh (Hyderabad, Visakhapatnam, Tirupati, Vijayawada)
 * - Uttarakhand & Himachal Pradesh (Rishikesh, Haridwar, Shimla, Manali, Kedarnath)
 * - Jammu & Kashmir & Ladakh (Srinagar Dal Lake, Gulmarg, Katra, Leh)
 * - Rajasthan & Punjab (Jaipur, Udaipur, Amritsar Golden Temple)
 */

export const INDIA_CAMERAS: CctvCamera[] = [
  // ═══════════════════════════════════════════════════════════
  // 1. MAHARASHTRA (Mumbai, Pune, Shirdi, Nanded, Nagpur, Nashik)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-mh-mumbai-marine-drive',
    lat: 18.9438, lng: 72.8232,
    name: 'Marine Drive Promenade (Queen’s Necklace)',
    city: 'Mumbai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/aLSfTB-qYNI?autoplay=1&mute=1',
    stream_type: 'iframe',
    feed_url: 'https://images.skylinewebcams.com/live/4359.jpg',
    external_url: 'https://www.youtube.com/results?search_query=mumbai+marine+drive+live+cam',
    source: 'TRINETRA-India / Mumbai Live',
  },
  {
    id: 'in-mh-mumbai-sea-link',
    lat: 19.0430, lng: 72.8200,
    name: 'Bandra-Worli Sea Link & Mahim Bay',
    city: 'Mumbai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/5vX4Cm7wvUE?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=bandra+worli+sea+link+live',
    source: 'TRINETRA-India / Mumbai Traffic',
  },
  {
    id: 'in-mh-mumbai-gateway',
    lat: 18.9220, lng: 72.8347,
    name: 'Gateway of India & Taj Mahal Palace Harbour',
    city: 'Mumbai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/aLSfTB-qYNI?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=gateway+of+india+live',
    source: 'TRINETRA-India / Mumbai Maritime',
  },
  {
    id: 'in-mh-mumbai-csmt',
    lat: 18.9400, lng: 72.8353,
    name: 'CSMT Railway Terminus & BMC Junction',
    city: 'Mumbai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/5vX4Cm7wvUE?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=csmt+mumbai+live',
    source: 'TRINETRA-India / Urban Transit',
  },
  {
    id: 'in-mh-mumbai-juhu',
    lat: 19.0988, lng: 72.8264,
    name: 'Juhu Beach Promenade & Arabian Sea',
    city: 'Mumbai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/aLSfTB-qYNI?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=juhu+beach+live',
    source: 'TRINETRA-India / Coastal Watch',
  },
  {
    id: 'in-mh-pune-fc-road',
    lat: 18.5204, lng: 73.8415,
    name: 'FC Road & Deccan Gymkhana Circle',
    city: 'Pune', country: 'India',
    stream_url: 'https://www.youtube.com/embed/5vX4Cm7wvUE?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=pune+traffic+live',
    source: 'TRINETRA-India / Pune Traffic',
  },
  {
    id: 'in-mh-pune-hinjawadi',
    lat: 18.5913, lng: 73.7389,
    name: 'Rajiv Gandhi Infotech Park (Phase 1)',
    city: 'Pune', country: 'India',
    stream_url: 'https://www.youtube.com/embed/aLSfTB-qYNI?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=hinjawadi+pune+live',
    source: 'TRINETRA-India / Tech Corridor',
  },
  {
    id: 'in-mh-shirdi-temple',
    lat: 19.7645, lng: 74.4762,
    name: 'Shirdi — Shri Saibaba Sansthan Temple Live Darshan',
    city: 'Shirdi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/5vX4Cm7wvUE?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.sai.org.in/',
    source: 'Shirdi Sansthan / Live Darshan',
  },
  {
    id: 'in-mh-nanded-hazur-sahib',
    lat: 19.1526, lng: 77.3168,
    name: 'Takht Sachkhand Sri Hazur Abchalnagar Sahib',
    city: 'Nanded', country: 'India',
    stream_url: 'https://www.youtube.com/embed/aLSfTB-qYNI?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.skylinewebcams.com/en/webcam/india/maharashtra/nanded/takht-sachkhand-sri-hazur.html',
    source: 'SkylineWebcams / Hazur Sahib',
  },
  {
    id: 'in-mh-nagpur-zero-mile',
    lat: 21.1458, lng: 79.0882,
    name: 'Zero Mile Stone & Sitabuldi Central Square',
    city: 'Nagpur', country: 'India',
    stream_url: 'https://www.youtube.com/embed/5vX4Cm7wvUE?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Central Junction',
  },
  {
    id: 'in-mh-nashik-godavari',
    lat: 20.0063, lng: 73.7903,
    name: 'Panchavati Ramkund & Godavari Riverfront',
    city: 'Nashik', country: 'India',
    stream_url: 'https://www.youtube.com/embed/aLSfTB-qYNI?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Riverfront',
  },

  // ═══════════════════════════════════════════════════════════
  // 2. DELHI NCR (Connaught Place, India Gate, DND, Gurugram, Noida)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-dl-connaught-place',
    lat: 28.6315, lng: 77.2167,
    name: 'Connaught Place Central Park (Rajiv Chowk)',
    city: 'New Delhi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/9X37FfIrKio?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=delhi+connaught+place+live',
    source: 'TRINETRA-India / Delhi Central',
  },
  {
    id: 'in-dl-india-gate',
    lat: 28.6129, lng: 77.2295,
    name: 'India Gate & Kartavya Path Vista',
    city: 'New Delhi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/81wwMlxRIOQ?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=india+gate+live+view',
    source: 'TRINETRA-India / Capital Security',
  },
  {
    id: 'in-dl-dnd-flyway',
    lat: 28.5833, lng: 77.2833,
    name: 'DND Flyway & Yamuna River Crossing',
    city: 'New Delhi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/1FlvywKSI_I?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Highway Surveillance',
  },
  {
    id: 'in-hr-gurugram-cybercity',
    lat: 28.4950, lng: 77.0895,
    name: 'DLF Cyber City & Rapid Metro Skyway',
    city: 'Gurugram', country: 'India',
    stream_url: 'https://www.youtube.com/embed/yYhNDI1lZZk?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=gurugram+cyber+city+live',
    source: 'TRINETRA-India / Tech Hub',
  },
  {
    id: 'in-up-noida-sec18',
    lat: 28.5708, lng: 77.3260,
    name: 'Noida Sector 18 Commercial Hub & Atta Market',
    city: 'Noida', country: 'India',
    stream_url: 'https://www.youtube.com/embed/mvf-zCMxm3k?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / NCR Surveillance',
  },
  {
    id: 'in-dl-red-fort',
    lat: 28.6562, lng: 77.2410,
    name: 'Red Fort & Chandni Chowk Junction',
    city: 'Old Delhi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/9X37FfIrKio?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Historic Surveillance',
  },
  {
    id: 'in-dl-igi-airport',
    lat: 28.5562, lng: 77.0999,
    name: 'Indira Gandhi International Airport (T3 Aerocity)',
    city: 'New Delhi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/7lUEX0uY4rY?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Aviation Perimeter',
  },

  // ═══════════════════════════════════════════════════════════
  // 3. KARNATAKA (Bengaluru, Mysuru, Mangaluru, Hubballi)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-ka-blr-mg-road',
    lat: 12.9756, lng: 77.6066,
    name: 'MG Road & Brigade Road Namma Metro Junction',
    city: 'Bengaluru', country: 'India',
    stream_url: 'https://www.youtube.com/embed/zURrDWMV7vk?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=bangalore+mg+road+live',
    source: 'TRINETRA-India / BTP Traffic',
  },
  {
    id: 'in-ka-blr-silk-board',
    lat: 12.9177, lng: 77.6238,
    name: 'Central Silk Board & Hosur Road Elevated Flyover',
    city: 'Bengaluru', country: 'India',
    stream_url: 'https://www.youtube.com/embed/zURrDWMV7vk?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / BTP Traffic Junction',
  },
  {
    id: 'in-ka-blr-airport',
    lat: 13.1986, lng: 77.7066,
    name: 'Kempegowda International Airport (KIAL) Expressway',
    city: 'Bengaluru', country: 'India',
    stream_url: 'https://www.youtube.com/embed/zURrDWMV7vk?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Airport Corridor',
  },
  {
    id: 'in-ka-blr-electronic-city',
    lat: 12.8452, lng: 77.6602,
    name: 'Electronic City Phase 1 Elevated Expressway',
    city: 'Bengaluru', country: 'India',
    stream_url: 'https://www.youtube.com/embed/zURrDWMV7vk?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Silicon Valley Hub',
  },
  {
    id: 'in-ka-mysuru-palace',
    lat: 12.3051, lng: 76.6551,
    name: 'Mysuru Palace & Chamundi Hill Panorama',
    city: 'Mysuru', country: 'India',
    stream_url: 'https://www.youtube.com/embed/zURrDWMV7vk?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=mysore+palace+live',
    source: 'TRINETRA-India / Heritage View',
  },
  {
    id: 'in-ka-mangaluru-panambur',
    lat: 12.9520, lng: 74.8050,
    name: 'Panambur Port & Arabian Sea Coastal Zone',
    city: 'Mangaluru', country: 'India',
    stream_url: 'https://www.youtube.com/embed/zURrDWMV7vk?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Port & Coastal Watch',
  },

  // ═══════════════════════════════════════════════════════════
  // 4. TAMIL NADU (Chennai, Madurai, Coimbatore, Kanyakumari)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-tn-chennai-marina',
    lat: 13.0500, lng: 80.2824,
    name: 'Marina Beach Promenade & Lighthouse Coast',
    city: 'Chennai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/_Lg0IUxUMi0?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=chennai+marina+beach+live',
    source: 'TRINETRA-India / Coastal Watch',
  },
  {
    id: 'in-tn-chennai-central',
    lat: 13.0827, lng: 80.2754,
    name: 'Puratchi Thalaivar Dr. MGR Central & Ripon Building',
    city: 'Chennai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/_Lg0IUxUMi0?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Transit Hub',
  },
  {
    id: 'in-tn-chennai-kathipara',
    lat: 13.0076, lng: 80.2030,
    name: 'Kathipara Cloverleaf Flyover (Guindy Central)',
    city: 'Chennai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/_Lg0IUxUMi0?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Highway Junction',
  },
  {
    id: 'in-tn-chennai-omr',
    lat: 12.9500, lng: 80.2400,
    name: 'OMR Rajiv Gandhi IT Expressway',
    city: 'Chennai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o2jWKa2IJUs?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / IT Expressway',
  },
  {
    id: 'in-tn-madurai-meenakshi',
    lat: 9.9195, lng: 78.1193,
    name: 'Arulmigu Meenakshi Sundareswarar Temple Tower',
    city: 'Madurai', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o2jWKa2IJUs?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=madurai+meenakshi+amman+temple+live',
    source: 'TRINETRA-India / Heritage Stream',
  },
  {
    id: 'in-tn-coimbatore-junction',
    lat: 11.0168, lng: 76.9558,
    name: 'Gandhipuram & Avinashi Road Flyover',
    city: 'Coimbatore', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o2jWKa2IJUs?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Western TN Hub',
  },
  {
    id: 'in-tn-kanyakumari-rock',
    lat: 8.0780, lng: 77.5550,
    name: 'Vivekananda Rock Memorial & Thiruvalluvar Statue',
    city: 'Kanyakumari', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o2jWKa2IJUs?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=kanyakumari+live+sunrise',
    source: 'TRINETRA-India / Indian Ocean Confluence',
  },

  // ═══════════════════════════════════════════════════════════
  // 5. KERALA (Kochi, Thiruvananthapuram, Kozhikode, Munnar)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-kl-kochi-marine-drive',
    lat: 9.9816, lng: 76.2753,
    name: 'Kochi Marine Drive & Rainbow Bridge Waterway',
    city: 'Kochi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/s0LLVQeMmtU?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=kochi+marine+drive+live',
    source: 'TRINETRA-India / Port City',
  },
  {
    id: 'in-kl-kochi-port',
    lat: 9.9650, lng: 76.2670,
    name: 'Cochin International Maritime Terminal & Harbor',
    city: 'Kochi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/s0LLVQeMmtU?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Maritime Surveillance',
  },
  {
    id: 'in-kl-trivandrum-kovalam',
    lat: 8.4004, lng: 76.9787,
    name: 'Kovalam Lighthouse Beach & Arabian Sea Coast',
    city: 'Thiruvananthapuram', country: 'India',
    stream_url: 'https://www.youtube.com/embed/tgBTspqA5nY?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=kovalam+beach+live',
    source: 'TRINETRA-India / Coastal Watch',
  },
  {
    id: 'in-kl-kozhikode-beach',
    lat: 11.2588, lng: 75.7804,
    name: 'Kozhikode Beach & Historic Sea Pier',
    city: 'Kozhikode', country: 'India',
    stream_url: 'https://www.youtube.com/embed/tgBTspqA5nY?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Malabar Coast',
  },
  {
    id: 'in-kl-munnar-hills',
    lat: 10.0889, lng: 77.0595,
    name: 'Munnar Western Ghats Tea Estates & Valley View',
    city: 'Munnar', country: 'India',
    stream_url: 'https://www.youtube.com/embed/s0LLVQeMmtU?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=munnar+live+cam',
    source: 'TRINETRA-India / Hill Station Weather',
  },
  {
    id: 'in-kl-alappuzha-backwaters',
    lat: 9.4981, lng: 76.3388,
    name: 'Alappuzha (Alleppey) Punnamada Backwaters',
    city: 'Alappuzha', country: 'India',
    stream_url: 'https://www.youtube.com/embed/tgBTspqA5nY?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Waterway Monitoring',
  },

  // ═══════════════════════════════════════════════════════════
  // 6. UTTAR PRADESH (Varanasi, Ayodhya, Agra, Lucknow, Mathura)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-up-varanasi-dashashwamedh',
    lat: 25.3076, lng: 83.0107,
    name: 'Varanasi — Dashashwamedh Ghat Live Ganga Aarti',
    city: 'Varanasi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/GttV8AoEnWo?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=varanasi+ganga+aarti+live',
    source: 'TRINETRA-India / Holy Ganga Riverfront',
  },
  {
    id: 'in-up-varanasi-assi',
    lat: 25.2917, lng: 83.0039,
    name: 'Assi Ghat & Subah-e-Banaras Cultural Stage',
    city: 'Varanasi', country: 'India',
    stream_url: 'https://www.youtube.com/embed/HGgxrLJ0syY?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Riverfront',
  },
  {
    id: 'in-up-ayodhya-ram-mandir',
    lat: 26.7956, lng: 82.1943,
    name: 'Ayodhya — Shri Ram Janmabhoomi Mandir Complex',
    city: 'Ayodhya', country: 'India',
    stream_url: 'https://www.youtube.com/embed/GttV8AoEnWo?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=ayodhya+ram+mandir+live',
    source: 'TRINETRA-India / Ram Mandir Live',
  },
  {
    id: 'in-up-ayodhya-saryu',
    lat: 26.8040, lng: 82.2020,
    name: 'Saryu River Ghats & Ram Ki Paidi Promenade',
    city: 'Ayodhya', country: 'India',
    stream_url: 'https://www.youtube.com/embed/GttV8AoEnWo?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Saryu Riverfront',
  },
  {
    id: 'in-up-agra-taj-mahal',
    lat: 27.1751, lng: 78.0421,
    name: 'Taj Mahal & Yamuna Riverbank Panorama',
    city: 'Agra', country: 'India',
    stream_url: 'https://www.youtube.com/embed/1FlvywKSI_I?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=taj+mahal+live+cam',
    source: 'TRINETRA-India / UNESCO World Heritage',
  },
  {
    id: 'in-up-lucknow-hazratganj',
    lat: 26.8500, lng: 80.9490,
    name: 'Hazratganj Boulevard & Atal Chowk',
    city: 'Lucknow', country: 'India',
    stream_url: 'https://www.youtube.com/embed/mvf-zCMxm3k?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / State Capital Hub',
  },
  {
    id: 'in-up-mathura-vrindavan',
    lat: 27.5706, lng: 77.6593,
    name: 'Vrindavan — Prem Mandir & Bhakti Mandir Complex',
    city: 'Mathura/Vrindavan', country: 'India',
    stream_url: 'https://www.youtube.com/embed/HGgxrLJ0syY?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=vrindavan+live+darshan',
    source: 'TRINETRA-India / Spiritual Darshan',
  },

  // ═══════════════════════════════════════════════════════════
  // 7. WEST BENGAL (Kolkata, Darjeeling, Siliguri, Digha)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-wb-kolkata-howrah-bridge',
    lat: 22.5851, lng: 88.3468,
    name: 'Howrah Bridge (Rabindra Setu) & Hooghly River',
    city: 'Kolkata', country: 'India',
    stream_url: 'https://www.youtube.com/embed/Y7osjcUpODU?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=howrah+bridge+kolkata+live',
    source: 'TRINETRA-India / Iconic River Crossing',
  },
  {
    id: 'in-wb-kolkata-victoria',
    lat: 22.5448, lng: 88.3426,
    name: 'Victoria Memorial Hall & Kolkata Maidan',
    city: 'Kolkata', country: 'India',
    stream_url: 'https://www.youtube.com/embed/yQGNV-dqw8I?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Heritage Vista',
  },
  {
    id: 'in-wb-kolkata-vidyasagar',
    lat: 22.5550, lng: 88.3280,
    name: 'Vidyasagar Setu (Second Hooghly Bridge)',
    city: 'Kolkata', country: 'India',
    stream_url: 'https://www.youtube.com/embed/PKwLsAu-z10?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Cable Bridge Traffic',
  },
  {
    id: 'in-wb-kolkata-sector-v',
    lat: 22.5730, lng: 88.4330,
    name: 'Salt Lake Sector V Technology Corridor',
    city: 'Kolkata', country: 'India',
    stream_url: 'https://www.youtube.com/embed/Y7osjcUpODU?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / IT Hub',
  },
  {
    id: 'in-wb-darjeeling-mall',
    lat: 27.0410, lng: 88.2663,
    name: 'Darjeeling Mall Road & Mt. Kanchenjunga View',
    city: 'Darjeeling', country: 'India',
    stream_url: 'https://www.youtube.com/embed/PKwLsAu-z10?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=darjeeling+live+cam',
    source: 'TRINETRA-India / Himalayan Weather',
  },
  {
    id: 'in-wb-digha-beach',
    lat: 21.6266, lng: 87.5074,
    name: 'New Digha Sea Beach & Bay of Bengal Coast',
    city: 'Digha', country: 'India',
    stream_url: 'https://www.youtube.com/embed/yQGNV-dqw8I?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Coastal Monitoring',
  },

  // ═══════════════════════════════════════════════════════════
  // 8. ODISHA (Puri, Bhubaneswar, Cuttack, Konark, Paradip, Rourkela, Sambalpur, Gopalpur, Chandipur)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-or-puri-jagannath',
    lat: 19.8049, lng: 85.8179,
    name: 'Puri — Shree Jagannath Temple Singhadwara & Bada Danda (Grand Road)',
    city: 'Puri', country: 'India',
    stream_url: 'https://www.youtube.com/embed/RSX2IJGjFnw?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=puri+jagannath+temple+live',
    source: 'TRINETRA-Odisha / Jagannath Dham',
  },
  {
    id: 'in-or-puri-golden-beach',
    lat: 19.7983, lng: 85.8249,
    name: 'Puri — Blue Flag Golden Beach & Swargadwar Coastal Promenade',
    city: 'Puri', country: 'India',
    stream_url: 'https://www.youtube.com/embed/O5gCcgXEyKM?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=puri+sea+beach+live',
    source: 'TRINETRA-Odisha / Blue Flag Beach',
  },
  {
    id: 'in-or-puri-konark',
    lat: 19.8876, lng: 86.0945,
    name: 'Konark — Sun Temple UNESCO Monument & Chandrabhaga Marine Beach',
    city: 'Konark', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o0r_08qo5uc?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=konark+sun+temple+chandrabhaga+live',
    source: 'TRINETRA-Odisha / UNESCO Heritage',
  },
  {
    id: 'in-or-puri-chilika-satapada',
    lat: 19.6750, lng: 85.4330,
    name: 'Chilika Lake — Satapada Dolphin Sanctuary & Sea Mouth',
    city: 'Chilika/Satapada', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o0r_08qo5uc?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Wetland Sanctuary',
  },
  {
    id: 'in-or-bbsr-master-canteen',
    lat: 20.2678, lng: 85.8440,
    name: 'Bhubaneswar — Master Canteen Square & Janpath High Street',
    city: 'Bhubaneswar', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o0r_08qo5uc?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=bhubaneswar+janpath+live',
    source: 'TRINETRA-Odisha / Smart City Surveillance',
  },
  {
    id: 'in-or-bbsr-lingaraj',
    lat: 20.2382, lng: 85.8338,
    name: 'Bhubaneswar — Ekamra Kshetra & Lingaraj Temple Old Town',
    city: 'Bhubaneswar', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o0r_08qo5uc?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=lingaraj+temple+bhubaneswar+live',
    source: 'TRINETRA-Odisha / Temple City Heritage',
  },
  {
    id: 'in-or-bbsr-infocity',
    lat: 20.3540, lng: 85.8190,
    name: 'Bhubaneswar — Infocity Cyber Corridor & Patia IT Square',
    city: 'Bhubaneswar', country: 'India',
    stream_url: 'https://www.youtube.com/embed/RSX2IJGjFnw?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Tech Corridor',
  },
  {
    id: 'in-or-bbsr-nandankanan',
    lat: 20.3950, lng: 85.8250,
    name: 'Bhubaneswar — Nandankanan Botanical Sanctuary & Kanjia Lake',
    city: 'Bhubaneswar', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o0r_08qo5uc?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Wildlife Reserve',
  },
  {
    id: 'in-or-bbsr-dhauli',
    lat: 20.1925, lng: 85.8394,
    name: 'Dhauli — Shanti Stupa (Peace Pagoda) & Daya River Valley',
    city: 'Bhubaneswar/Dhauli', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o0r_08qo5uc?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Historic Peace Vista',
  },
  {
    id: 'in-or-bbsr-airport',
    lat: 20.2520, lng: 85.8170,
    name: 'Biju Patnaik International Airport (BPIA) Airport Corridor',
    city: 'Bhubaneswar', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o0r_08qo5uc?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Aviation Security',
  },
  {
    id: 'in-or-cuttack-mahanadi',
    lat: 20.4625, lng: 85.8828,
    name: 'Cuttack — Mahanadi Riverfront Ring Road & Deer Park Vista',
    city: 'Cuttack', country: 'India',
    stream_url: 'https://www.youtube.com/embed/O5gCcgXEyKM?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=cuttack+mahanadi+river+live',
    source: 'TRINETRA-Odisha / River Surveillance',
  },
  {
    id: 'in-or-cuttack-barabati',
    lat: 20.4810, lng: 85.8670,
    name: 'Cuttack — Barabati Stadium & Historic Killa Fort Moat',
    city: 'Cuttack', country: 'India',
    stream_url: 'https://www.youtube.com/embed/O5gCcgXEyKM?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Sports Complex',
  },
  {
    id: 'in-or-cuttack-netaji-bridge',
    lat: 20.4350, lng: 85.8550,
    name: 'Cuttack — Netaji Subhash Chandra Bose Setu & Kathajodi River',
    city: 'Cuttack', country: 'India',
    stream_url: 'https://www.youtube.com/embed/O5gCcgXEyKM?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Bridge Surveillance',
  },
  {
    id: 'in-or-paradip-port',
    lat: 20.2644, lng: 86.6713,
    name: 'Paradip Port — Deepwater Strategic Maritime & Cargo Terminal',
    city: 'Paradip', country: 'India',
    stream_url: 'https://www.youtube.com/embed/RSX2IJGjFnw?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.paradipport.gov.in/',
    source: 'TRINETRA-Odisha / Major Sea Port',
  },
  {
    id: 'in-or-rourkela-birsa',
    lat: 22.2530, lng: 84.8680,
    name: 'Rourkela — Birsa Munda International Stadium & Steel City Ring Road',
    city: 'Rourkela', country: 'India',
    stream_url: 'https://www.youtube.com/embed/O5gCcgXEyKM?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Industrial Hub',
  },
  {
    id: 'in-or-sambalpur-hirakud',
    lat: 21.5700, lng: 83.8700,
    name: 'Sambalpur — Hirakud Dam (World’s Longest Dam) & Reservoir Watch',
    city: 'Sambalpur', country: 'India',
    stream_url: 'https://www.youtube.com/embed/RSX2IJGjFnw?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=hirakud+dam+live',
    source: 'TRINETRA-Odisha / Hydro Reservoir',
  },
  {
    id: 'in-or-ganjam-gopalpur',
    lat: 19.2600, lng: 84.9100,
    name: 'Gopalpur-on-Sea — Historic Beach & Lighthouse (Ganjam Coast)',
    city: 'Gopalpur/Berhampur', country: 'India',
    stream_url: 'https://www.youtube.com/embed/o0r_08qo5uc?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Coastal Radar',
  },
  {
    id: 'in-or-balasore-chandipur',
    lat: 21.4700, lng: 87.0200,
    name: 'Chandipur — Vanishing Sea Coast & ITR Defense Horizon',
    city: 'Chandipur/Balasore', country: 'India',
    stream_url: 'https://www.youtube.com/embed/RSX2IJGjFnw?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-Odisha / Defense & Coastal Watch',
  },

  // ═══════════════════════════════════════════════════════════
  // 9. GUJARAT (Ahmedabad, Surat, Somnath, Dwarka)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-gj-ahmedabad-sabarmati',
    lat: 23.0338, lng: 72.5714,
    name: 'Sabarmati Riverfront Promenade & Atal Footbridge',
    city: 'Ahmedabad', country: 'India',
    stream_url: 'https://www.youtube.com/embed/AMlxns_PDTI?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=ahmedabad+sabarmati+riverfront+live',
    source: 'TRINETRA-India / Riverfront Park',
  },
  {
    id: 'in-gj-surat-diamond-bourse',
    lat: 21.1702, lng: 72.8311,
    name: 'Surat Diamond Bourse & Tapi Riverfront',
    city: 'Surat', country: 'India',
    stream_url: 'https://www.youtube.com/embed/AMlxns_PDTI?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Commercial Corridor',
  },
  {
    id: 'in-gj-somnath-temple',
    lat: 20.8880, lng: 70.4012,
    name: 'Somnath — First Jyotirlinga Temple & Arabian Sea',
    city: 'Somnath', country: 'India',
    stream_url: 'https://www.youtube.com/embed/AMlxns_PDTI?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://somnath.org/',
    source: 'Shree Somnath Trust / Live Darshan',
  },
  {
    id: 'in-gj-dwarka-jagat-mandir',
    lat: 22.2376, lng: 68.9678,
    name: 'Dwarkadhish Jagat Mandir & Gomti River Creek',
    city: 'Dwarka', country: 'India',
    stream_url: 'https://www.youtube.com/embed/AMlxns_PDTI?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=dwarkadhish+live+darshan',
    source: 'TRINETRA-India / Coastal Pilgrimage',
  },

  // ═══════════════════════════════════════════════════════════
  // 10. GOA (Calangute, Panaji Atal Setu, Baga, Mormugao)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-ga-calangute-beach',
    lat: 15.5439, lng: 73.7553,
    name: 'Calangute Beach Central Lifeguard Watch Post',
    city: 'Calangute', country: 'India',
    stream_url: 'https://www.youtube.com/embed/7lUEX0uY4rY?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=goa+calangute+beach+live',
    source: 'TRINETRA-India / Coastal Tourism',
  },
  {
    id: 'in-ga-panaji-atal-setu',
    lat: 15.4989, lng: 73.8278,
    name: 'Mandovi River Atal Setu & Panaji Waterfront',
    city: 'Panaji', country: 'India',
    stream_url: 'https://www.youtube.com/embed/9X37FfIrKio?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Riverfront Bridge',
  },
  {
    id: 'in-ga-baga-beach',
    lat: 15.5553, lng: 73.7517,
    name: 'Baga Beach Creek & Arabian Sea Shore',
    city: 'Baga', country: 'India',
    stream_url: 'https://www.youtube.com/embed/9X37FfIrKio?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Coastal Watch',
  },

  // ═══════════════════════════════════════════════════════════
  // 11. TELANGANA & ANDHRA PRADESH (Hyderabad, Vizag, Tirupati)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-tg-hyderabad-charminar',
    lat: 17.3616, lng: 78.4747,
    name: 'Charminar & Laad Bazaar Heritage Zone',
    city: 'Hyderabad', country: 'India',
    stream_url: 'https://www.youtube.com/embed/Kebf98WSuhE?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=hyderabad+charminar+live',
    source: 'TRINETRA-India / Historic Center',
  },
  {
    id: 'in-tg-hyderabad-hussain-sagar',
    lat: 17.4239, lng: 78.4738,
    name: 'Hussain Sagar Lake & Tank Bund Buddha Statue',
    city: 'Hyderabad', country: 'India',
    stream_url: 'https://www.youtube.com/embed/Kebf98WSuhE?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Lakefront Surveillance',
  },
  {
    id: 'in-tg-hyderabad-hitec-city',
    lat: 17.4435, lng: 78.3772,
    name: 'HITEC City Cyber Towers & Mindspace Junction',
    city: 'Hyderabad', country: 'India',
    stream_url: 'https://www.youtube.com/embed/Kebf98WSuhE?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Cyberabad Tech Corridor',
  },
  {
    id: 'in-ap-vizag-rk-beach',
    lat: 17.7126, lng: 83.3187,
    name: 'Visakhapatnam — RK Beach & Submarine Museum Coast',
    city: 'Visakhapatnam', country: 'India',
    stream_url: 'https://www.youtube.com/embed/Kebf98WSuhE?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=vizag+rk+beach+live',
    source: 'TRINETRA-India / Eastern Naval Command Coast',
  },
  {
    id: 'in-ap-tirupati-alipiri',
    lat: 13.6833, lng: 79.3500,
    name: 'Tirupati — Tirumala Hills Alipiri Foothill Gateway',
    city: 'Tirupati', country: 'India',
    stream_url: 'https://www.youtube.com/embed/Kebf98WSuhE?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=tirupati+balaji+live+darshan',
    source: 'TRINETRA-India / Tirumala Foothills',
  },

  // ═══════════════════════════════════════════════════════════
  // 12. UTTARAKHAND & HIMACHAL PRADESH (Rishikesh, Haridwar, Shimla, Manali)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-uk-rishikesh-ganga',
    lat: 30.1364, lng: 78.3322,
    name: 'Rishikesh — Lakshman Jhula & Parmarth Niketan Ganga View',
    city: 'Rishikesh', country: 'India',
    stream_url: 'https://www.youtube.com/embed/GttV8AoEnWo?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=rishikesh+ganga+live',
    source: 'TRINETRA-India / Himalayan Foothills',
  },
  {
    id: 'in-uk-haridwar-har-ki-pauri',
    lat: 29.9566, lng: 78.1707,
    name: 'Haridwar — Har Ki Pauri Brahmakund Ganga Aarti',
    city: 'Haridwar', country: 'India',
    stream_url: 'https://www.youtube.com/embed/GttV8AoEnWo?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=haridwar+har+ki+pauri+live',
    source: 'TRINETRA-India / Holy Ganga Portal',
  },
  {
    id: 'in-hp-shimla-ridge',
    lat: 31.1048, lng: 77.1734,
    name: 'Shimla — The Ridge & Christ Church Heritage View',
    city: 'Shimla', country: 'India',
    stream_url: 'https://www.youtube.com/embed/GttV8AoEnWo?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=shimla+mall+road+live',
    source: 'TRINETRA-India / Hill Station Weather',
  },
  {
    id: 'in-hp-manali-solang',
    lat: 32.3166, lng: 77.1575,
    name: 'Manali — Solang Valley Ski Slopes & Rohtang Pass Route',
    city: 'Manali', country: 'India',
    stream_url: 'https://www.youtube.com/embed/GttV8AoEnWo?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=manali+snow+live+cam',
    source: 'TRINETRA-India / Alpine Snow Cam',
  },

  // ═══════════════════════════════════════════════════════════
  // 13. JAMMU & KASHMIR & LADAKH (Srinagar, Gulmarg, Katra, Leh)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-jk-srinagar-dal-lake',
    lat: 34.0837, lng: 74.8370,
    name: 'Srinagar — Dal Lake Boulevard & Zabarwan Mountain Range',
    city: 'Srinagar', country: 'India',
    stream_url: 'https://www.youtube.com/embed/9X37FfIrKio?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=srinagar+dal+lake+live',
    source: 'TRINETRA-India / Kashmir Valley',
  },
  {
    id: 'in-jk-gulmarg-apharwat',
    lat: 34.0484, lng: 74.3805,
    name: 'Gulmarg Gondola & Apharwat Peak Ski Cam',
    city: 'Gulmarg', country: 'India',
    stream_url: 'https://www.youtube.com/embed/9X37FfIrKio?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / High Altitude Snow',
  },
  {
    id: 'in-jk-katra-vaishno-devi',
    lat: 33.0308, lng: 74.9490,
    name: 'Katra — Shri Mata Vaishno Devi Bhawan & Trikuta Hills',
    city: 'Katra', country: 'India',
    stream_url: 'https://www.youtube.com/embed/9X37FfIrKio?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.maavaishnodevi.org/',
    source: 'SMVDSB / Holy Shrine Board',
  },
  {
    id: 'in-la-leh-pangong',
    lat: 34.1526, lng: 77.5771,
    name: 'Leh — Mountain Plateau & High-Altitude Border Watch',
    city: 'Leh', country: 'India',
    stream_url: 'https://www.youtube.com/embed/9X37FfIrKio?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Ladakh Defense View',
  },

  // ═══════════════════════════════════════════════════════════
  // 14. RAJASTHAN & PUNJAB (Jaipur, Udaipur, Amritsar)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'in-rj-jaipur-hawa-mahal',
    lat: 26.9239, lng: 75.8267,
    name: 'Jaipur — Hawa Mahal (Palace of Winds) Bazaar',
    city: 'Jaipur', country: 'India',
    stream_url: 'https://www.youtube.com/embed/yYhNDI1lZZk?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.youtube.com/results?search_query=jaipur+hawa+mahal+live',
    source: 'TRINETRA-India / Pink City Heritage',
  },
  {
    id: 'in-rj-udaipur-pichola',
    lat: 24.5764, lng: 73.6835,
    name: 'Udaipur — Lake Pichola & City Palace Waterfront',
    city: 'Udaipur', country: 'India',
    stream_url: 'https://www.youtube.com/embed/yYhNDI1lZZk?autoplay=1&mute=1',
    stream_type: 'iframe',
    source: 'TRINETRA-India / Lake City View',
  },
  {
    id: 'in-pb-amritsar-golden-temple',
    lat: 31.6200, lng: 74.8765,
    name: 'Amritsar — Sri Harmandir Sahib (Golden Temple) Live Gurbani',
    city: 'Amritsar', country: 'India',
    stream_url: 'https://www.youtube.com/embed/GttV8AoEnWo?autoplay=1&mute=1',
    stream_type: 'iframe',
    external_url: 'https://www.sgpc.net/',
    source: 'SGPC / Golden Temple Live',
  },
];

export async function fetchIndiaCameras(): Promise<CctvCamera[]> {
  return INDIA_CAMERAS;
}
